### ISSUE TITLE
Add dotenv module

### ISSUE THREAD

**Issue by R3dHash** [redrabytes/anqet#1]
Hi :),
I had to install this dependency to make it work:
```bash
sudo npm install dotenv
```
Cheeers!

**Comment by redrabytes** [comment]
Hello,

I updated it in package.json, thanks for your

**Comment by redrabytes** [comment]
Hi,

Thanks for your issues report, I fixed it in the `package.json`.
https://github.com/redrabytes/anqet/commit/caa7d8ecc29b67e58843a81f21a93c0c355069b2
